const mongoose = require("mongoose");
const { MONGO_URI } = require("../config");
const Suburb = require("../models/Suburb");

const suburbs = [
  // { suburb: "Peakhurst", postcode: "2210" },
  // { suburb: "Riverwood", postcode: "2210" },
  // { suburb: "Lugarno", postcode: "2210" },
  // { suburb: "Peakhurst Heights", postcode: "2210" },
  // { suburb: "Beverly Hills", postcode: "2209" },
  // { suburb: "Mortdale", postcode: "2223" },
  // { suburb: "Oatley", postcode: "2223" },
  // { suburb: "Hurstville Grove", postcode: "2220" },
  // { suburb: "Blakehurst", postcode: "2221" },
  // { suburb: "Picnic Point", postcode: "2213" },
  // { suburb: "Kingsgrove", postcode: "2208" },
  // { suburb: "Revesby", postcode: "2212" },
  // { suburb: "Connells Point", postcode: "2221" },
  // { suburb: "Hurstville", postcode: "2220" },
  // { suburb: "Padstow Heights", postcode: "2211" },
  // { suburb: "Padstow", postcode: "2211" },
  // { suburb: "Panania", postcode: "2213" },
  // { suburb: "Narwee", postcode: "2209" },
  // { suburb: "Werrington", postcode: "2747" },
  // { suburb: "Merrylands", postcode: "2160" },
  // { suburb: "Kyle Bay", postcode: "2221" },
  // { suburb: "South Hurstville", postcode: "2221" },
  // { suburb: "Penshurst", postcode: "2222" },
  // { suburb: "Denham Court", postcode: "2565" },
  // { suburb: "Leppington", postcode: "2179" },
  // { suburb: "Austral", postcode: "2179" },
  // { suburb: "Edmondson Park", postcode: "2174" },


    // { suburb: "Sylvania", postcode: "2224" },
    // { suburb: "Sylvania Waters", postcode: "2224" },
    // { suburb: "Kangaroo Point", postcode: "2224" },
    // { suburb: "Oran Park", postcode: "2570" },
    // { suburb: "Campbelltown", postcode: "2560" },
    // { suburb: "Padstow", postcode: "2211" },
    // { suburb: "Panania", postcode: "2213" },
    // { suburb: "Harrington Park", postcode: "2567" },
    // { suburb: "Kyle Bay", postcode: "2221" },
    // { suburb: "Gregory Hills", postcode: "2557" },
    // { suburb: "Hurstville", postcode: "2220" },
    // { suburb: "West Hoxton", postcode: "2171" },
    // { suburb: "Kogarah Bay", postcode: "2217" }


    // { suburb: "Airds", postcode: "2560" },
    // { suburb: "Alfords Point", postcode: "2234" },
    // { suburb: "Allawah", postcode: "2218" },
    // { suburb: "Ambarvale", postcode: "2560" },
    // { suburb: "Arncliffe", postcode: "2205" },
    // { suburb: "Ashcroft", postcode: "2168" },
    // { suburb: "Bangor", postcode: "2234" },
    // { suburb: "Banksia", postcode: "2216" },
    // { suburb: "Bankstown", postcode: "2200" },
    // { suburb: "Barden Ridge", postcode: "2234" },
    // { suburb: "Bardia", postcode: "2565" },
    // { suburb: "Bardwell Park", postcode: "2207" },
    // { suburb: "Bardwell Valley", postcode: "2207" },
    // { suburb: "Bass Hill", postcode: "2197" },
    // { suburb: "Bexley", postcode: "2207" },
    // { suburb: "Bexley North", postcode: "2207" },
    // { suburb: "Birrong", postcode: "2143" },
    // { suburb: "Blair Athol", postcode: "2560" },
    // { suburb: "Blairmount", postcode: "2559" },
    // { suburb: "Bonnet Bay", postcode: "2226" },
    // { suburb: "Bow Bowing", postcode: "2566" },
    // { suburb: "Bradbury", postcode: "2560" },
    // { suburb: "Bundeena", postcode: "2230" },
    // { suburb: "Burraneer", postcode: "2230" }
  
  
    // { suburb: "Busby", postcode: "2168" },
    // { suburb: "Camden", postcode: "2570" },
    // { suburb: "Camden South", postcode: "2570" },
    // { suburb: "Caringbah", postcode: "2229" },
    // { suburb: "Caringbah South", postcode: "2229" },
    // { suburb: "Carlingford", postcode: "2118" },
    // { suburb: "Carlton", postcode: "2218" },
    // { suburb: "Carnes Hill", postcode: "2171" },
    // { suburb: "Carss Park", postcode: "2221" },
    // { suburb: "Casula", postcode: "2170" },
    // { suburb: "Catherine Field", postcode: "2557" },
    // { suburb: "Cecil Hills", postcode: "2171" },
    // { suburb: "Chester Hill", postcode: "2162" },
    // { suburb: "Chipping Norton", postcode: "2170" },
    // { suburb: "Claymore", postcode: "2559" },
    // { suburb: "Clyde", postcode: "2142" },
    // { suburb: "Como", postcode: "2226" },
    // { suburb: "Condell Park", postcode: "2200" },
    // { suburb: "Cronulla", postcode: "2230" },
    // { suburb: "Currans Hill", postcode: "2567" },
    // { suburb: "Dolans Bay", postcode: "2229" },
    // { suburb: "Dundas", postcode: "2117" },
    // { suburb: "Dundas Valley", postcode: "2117" },
    // { suburb: "Eagle Vale", postcode: "2558" },
    // { suburb: "Elderslie", postcode: "2570" },
    // { suburb: "Ellis Lane", postcode: "2570" },
    // { suburb: "Engadine", postcode: "2233" },
    // { suburb: "Englorie Park", postcode: "2560" },
    // { suburb: "Epping", postcode: "2121" },
    // { suburb: "Ermington", postcode: "2115" },
    // { suburb: "Eschol Park", postcode: "2558" },
    // { suburb: "Georges Hall", postcode: "2198" },
    // { suburb: "Gilead", postcode: "2560" },
    // { suburb: "Glen Alpine", postcode: "2560" },
    // { suburb: "Glenfield", postcode: "2167" },
    // { suburb: "Granville", postcode: "2142" },
    // { suburb: "Grays Point", postcode: "2232" },
    // { suburb: "Green Valley", postcode: "2168" },
    // { suburb: "Greenacre", postcode: "2190" },
    // { suburb: "Greenhills Beach", postcode: "2230" }

    // { suburb: "Guildford", postcode: "2161" },
    // { suburb: "Gymea", postcode: "2227" },
    // { suburb: "Gymea Bay", postcode: "2227" },
    // { suburb: "Hammondville", postcode: "2170" },
    // { suburb: "Harris Park", postcode: "2150" },
    // { suburb: "Heathcote", postcode: "2233" },
    // { suburb: "Heckenberg", postcode: "2168" },
    // { suburb: "Hinchinbrook", postcode: "2168" },
    // { suburb: "Holsworthy", postcode: "2173" },
    // { suburb: "Horningsea Park", postcode: "2171" },
    // { suburb: "Illawong", postcode: "2234" },
    // { suburb: "Ingleburn", postcode: "2565" },
    // { suburb: "Jannali", postcode: "2226" },
    // { suburb: "Kareela", postcode: "2232" },
    // { suburb: "Kearns", postcode: "2558" },
    // { suburb: "Kirrawee", postcode: "2232" },
    // { suburb: "Kogarah", postcode: "2217" },
    // { suburb: "Kurnell", postcode: "2231" },
    // { suburb: "Lakemba", postcode: "2195" },
    // { suburb: "Lansdowne", postcode: "2163" },
    // { suburb: "Leumeah", postcode: "2560" },
    // { suburb: "Lilli Pilli", postcode: "2229" },
    // { suburb: "Liverpool", postcode: "2170" },
    // { suburb: "Loftus", postcode: "2232" },
    // { suburb: "Long Point", postcode: "2564" },
    // { suburb: "Lucas Heights", postcode: "2234" },
    // { suburb: "Lurnea", postcode: "2170" },
    // { suburb: "Macarthur", postcode: "2560" },
    // { suburb: "Macquarie Fields", postcode: "2564" }


    // { suburb: "Macquarie Links", postcode: "2565" },
    // { suburb: "Maianbar", postcode: "2230" },
    // { suburb: "Mays Hill", postcode: "2145" },
    // { suburb: "Menai", postcode: "2234" },
    // { suburb: "Menangle", postcode: "2568" },
    // { suburb: "Merrylands", postcode: "2160" },
    // { suburb: "Middleton Grange", postcode: "2171" },
    // { suburb: "Miller", postcode: "2168" },
    // { suburb: "Milperra", postcode: "2214" },
    // { suburb: "Minto", postcode: "2566" },
    // { suburb: "Minto Heights", postcode: "2566" },
    // { suburb: "Miranda", postcode: "2228" },
    // { suburb: "Moorebank", postcode: "2170" },
    // { suburb: "Mount Annan", postcode: "2567" },
    // { suburb: "Mount Lewis", postcode: "2200" },
    // { suburb: "Narellan", postcode: "2567" },
    // { suburb: "Narellan Vale", postcode: "2567" },
    // { suburb: "North Parramatta", postcode: "2151" },
    // { suburb: "North Rocks", postcode: "2151" },
    // { suburb: "Northmead", postcode: "2152" },
    // { suburb: "Oatlands", postcode: "2117" },
    // { suburb: "Old Toongabbie", postcode: "2146" },
    // { suburb: "Oyster Bay", postcode: "2225" },
    // { suburb: "Parramatta", postcode: "2150" },
    // { suburb: "Port Hacking", postcode: "2229" },
    // { suburb: "Prestons", postcode: "2170" },
    // { suburb: "Punchbowl", postcode: "2196" },
    // { suburb: "Raby", postcode: "2566" },
    // { suburb: "Ramsgate", postcode: "2217" },
    // { suburb: "Ramsgate Beach", postcode: "2217" },
    // { suburb: "Revesby Heights", postcode: "2212" },
    // { suburb: "Rosehill", postcode: "2142" },
    // { suburb: "Roselands", postcode: "2196" },
    // { suburb: "Rosemeadow", postcode: "2560" },
    // { suburb: "Ruse", postcode: "2560" },
    // { suburb: "Rydalmere", postcode: "2116" },
    // { suburb: "Sadleir", postcode: "2168" },
    // { suburb: "Sandringham", postcode: "2219" },
    // { suburb: "Sandy Point", postcode: "2172" },
    // { suburb: "Sans Souci", postcode: "2219" }

    { suburb: "Sefton", postcode: "2162" },
    { suburb: "Smeaton Grange", postcode: "2567" },
    { suburb: "South Granville", postcode: "2142" },
    { suburb: "South Hurstville", postcode: "2221" },
    { suburb: "Spring Farm", postcode: "2570" },
    { suburb: "St Andrews", postcode: "2566" },
    { suburb: "St Helens Park", postcode: "2560" },
    { suburb: "Sutherland", postcode: "2232" },
    { suburb: "Taren Point", postcode: "2229" },
    { suburb: "Telopea", postcode: "2117" },
    { suburb: "Toongabbie", postcode: "2146" },
    { suburb: "Varroville", postcode: "2566" },
    { suburb: "Villawood", postcode: "2163" },
    { suburb: "Voyager Point", postcode: "2172" },
    { suburb: "Warwick Farm", postcode: "2170" },
    { suburb: "Waterfall", postcode: "2233" },
    { suburb: "Wattle Grove", postcode: "2173" },
    { suburb: "Westmead", postcode: "2145" },
    { suburb: "Wiley Park", postcode: "2195" },
    { suburb: "Winston Hills", postcode: "2153" },
    { suburb: "Woodbine", postcode: "2560" },
    { suburb: "Woolooware", postcode: "2230" },
    { suburb: "Woronora", postcode: "2232" },
    { suburb: "Woronora Heights", postcode: "2233" },
    { suburb: "Yagoona", postcode: "2199" },
    { suburb: "Yowie Bay", postcode: "2228" }
];

async function runMigration() {
  try {
    await mongoose.connect(MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    await Suburb.insertMany(suburbs);
    console.log("Migration completed successfully");
  } catch (error) {
    console.error("Migration failed:", error);
  } finally {
    mongoose.connection.close();
  }
}

runMigration();
